name: alpine-3.15

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 3.15
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ./alpine/3.15/
          push: true
          tags: kingstartech/cmake:alpine3.15
      -
        name: Build and push 3.16
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ./alpine/3.16/
          push: true
          tags: kingstartech/cmake:alpine3.16
