name: debian-buster

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 10
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ./debian/10/
          push: true
          tags: kingstartech/cmake:10
      -
        name: Build and push 11
        uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64/v8
          context: ./debian/11/
          push: true
          tags: kingstartech/cmake:11
